language: python
python:
  - "3.5"
dist: trusty
sudo: required
env:
  global:
    - SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.4.2/solc"
  matrix:
    - TOX_ENV=py35
    - TOX_ENV=flake8
cache:
  - pip: true
  - directories:
    - .tox
    - $TRAVIS_BUILD_DIR/solc-versions/solc-0.4.2
    - $TRAVIS_BUILD_DIR/solc-versions/solidity-0.4.2/build
install:
  - ./bin/install_solc-0.4.2.sh
  - travis_retry pip install setuptools --upgrade
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
before_script:
  - ls -lah $TRAVIS_BUILD_DIR/solc-versions/solc-0.3.6/
  - ./solc-versions/solc-0.4.2/solc --version
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
